server:
  port: 8081

spring:
  profiles:
    active: dev
  application:
    name: GitStarCenter
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${yiming1234.datasource.host}:${yiming1234.datasource.port}/${yiming1234.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${yiming1234.datasource.username}
    password: ${yiming1234.datasource.password}
  security:
    oauth2:
      client:
        registration:
          github:
            scope:
              - read:user
              - public_repo
              - user:follow
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"

logging:
  level:
    root: info
    cn.yiming1234.gitstarcenter: info
    org.springframework.security: debug
    org.springframework.web: debug

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: cn.yiming1234.gitstarcenter.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

yiming1234:
  mail:
    host: smtp.qq.com
    port: 465
    from: pleasurecruise@qq.com
    subject: Git Star Center 仓库互动提醒
