spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23ligixpQ2ec2dRxDf
            client-secret: d9b0ce5eb69fca0d801f111183fa2cd83472fb41

yiming1234:
  jwt:
    secret: pleasurecruise
    refreshExpiration: 2592000
  datasource:
    host: localhost
    port: 3306
    database: gitstarcenter
    username: gitstarcenter
    password: nY7k5PDcbGfecNC6
  mail:
    from: pleasure@yiming1234.cn
    username: pleasure@yiming1234.cn
    password: gqhxodrebfkmdehc