server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liggTqDGAFDlxMrF
            client-secret: 496bc3a1effb5d2534a22107e60211a94a7995d1

app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 3600000
  cors:
    allowedOrigins: http://localhost:5173
  oauth2:
    authorizedRedirectUris:
      - http://localhost:5173/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect

yiming1234:
  jwt:
    secret:
    refreshExpiration: 2592000
  datasource:
    host: localhost
    port: 3306
    database: gitstarcenter
    username:
    password:
  mail:
    username:
    password: