name: SpringBoot Built

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:

    permissions: write-all
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        repositories: ''
        servers: ''
    - name: Build with Maven
      run: mvn package -B -DskipTests --file pom.xml

    - name: copy jar via ssh password
      uses: appleboy/scp-action@v0.0.1
      with:
          host: 121.36.197.56
          username: pleasure
          password: Wym20050305@
          port: 22
          source: target/GitStarCenter-0.0.1-SNAPSHOT.jar
          target: /mnt/data/GitStarCenter

