name: SpringBoot Built

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:

    permissions: write-all
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        repositories: ''
        servers: ''
    - name: Build with Maven
      run: mvn package -B -DskipTests --file pom.xml

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to production server
      uses: appleboy/ssh-action@v0.1.6
      with:
          host: 121.36.197.56
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            scp -o StrictHostKeyChecking=no target/GitStarCenter-0.0.1-SNAPSHOT.jar ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/mnt/data/GitStarCenter/

            ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'

              cd /mnt/data/GitStarCenter

              /www/server/java/jdk-21.0.2/bin/java -jar GitStarCenter-0.0.1-SNAPSHOT.jar
            EOF
